FROM scratch

WORKDIR /app
COPY dist/linux-amd64/kids-poetry-api /app/server
COPY dist/linux-amd64/kids-poetry-importer /app/importer
COPY dist/linux-amd64/kids-poetry-minio-sync /app/minio-sync
COPY etc/backend.docker.yaml /app/etc/backend.yaml
USER 65532:65532
EXPOSE 8890
ENTRYPOINT ["/app/server"]
CMD ["-f", "/app/etc/backend.yaml"]
